// Code generated by go-bindata.
// sources:
// migrations_gateway/01_init.sql
// migrations_compliance/01_init.sql
// DO NOT EDIT!

package postgres

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _migrations_gateway01_initSql = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x7c\x92\x41\x4f\xc3\x30\x0c\x85\xef\xf9\x15\x3e\x6e\x82\x49\x80\xd8\x2e\x3b\x15\x16\xa4\x89\xb2\x8d\xd2\x1e\x76\xaa\xb2\xc4\x2a\x11\x6d\x52\x25\xee\x18\xff\x9e\x0c\x09\xd6\x86\xc1\x31\xfa\x5e\x6c\x3f\x3f\x4f\x26\x70\xd1\xe8\xca\x09\x42\x28\x5a\x76\x9f\xf1\x24\xe7\x90\x27\x77\x29\x87\x0c\x25\xea\x3d\xaa\x8d\xf8\x68\xd0\x10\x8c\x18\x80\x56\xb0\xd3\x95\x47\xa7\x45\x7d\x19\xde\xb6\xc5\xf0\x57\x5b\x53\x06\xb2\x17\x4e\xbe\x0a\x37\xba\x99\x4e\xc7\x50\xac\x96\xcf\x05\x87\xd5\x3a\x87\x55\x91\xa6\x47\x71\xeb\xac\x44\xef\x51\x95\x82\x80\x74\x83\x9e\x44\xd3\x0e\x25\xa2\xd2\xa6\x2a\xc9\xbe\xa1\x19\xd6\xeb\xab\xc2\x3f\xea\xfc\xdf\x7c\x93\x2d\x9f\x92\x6c\x0b\x8f\x7c\x0b\x23\xad\xc6\x6c\x3c\x67\x43\x6f\x2f\xc1\x50\xee\x84\xf1\x42\x1e\xa7\xff\xf6\x76\x32\x46\x27\xd8\xb7\x36\xbb\xed\x75\x82\xdf\xa3\x5c\x5f\x45\x93\xda\xce\x49\xfc\xc1\xd3\x59\x84\xbb\x5d\xa3\x89\xfe\xdb\x88\xef\xa4\x44\x54\xb1\x64\xc1\x1f\x92\x22\x3d\xc9\x6a\x54\x15\xba\x63\x38\x3a\x44\x15\x53\x34\x7b\xac\x43\x56\xe5\x41\x39\x20\x3c\xd0\xa0\x85\x43\xdf\xd5\xf4\xc5\x06\x2b\x8d\xab\x9c\x5d\x6b\xff\x82\x16\xf6\xdd\xb0\x45\xb6\xde\x9c\xbf\xa0\x79\x9f\x45\x09\xcc\xd9\x67\x00\x00\x00\xff\xff\x4d\x61\x55\x6b\x8b\x02\x00\x00")

func migrations_gateway01_initSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations_gateway01_initSql,
		"migrations_gateway/01_init.sql",
	)
}

func migrations_gateway01_initSql() (*asset, error) {
	bytes, err := migrations_gateway01_initSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations_gateway/01_init.sql", size: 651, mode: os.FileMode(420), modTime: time.Unix(1473881382, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _migrations_compliance01_initSql = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x94\x93\x5f\x6f\x82\x30\x14\xc5\xdf\xfb\x29\xee\xa3\x64\xfa\xb2\x4c\x5f\x7c\x62\x93\x25\x64\x0e\x1d\x81\x64\x3e\x91\xab\xed\xb4\x19\xa5\xa6\x96\xa9\xfb\xf4\x2b\xf3\x0f\xed\x14\xcc\x12\x5e\xe8\x3d\xf7\xde\x73\x7e\xd0\x5e\x0f\xee\x04\x5f\x2a\xd4\x0c\xd2\x35\x79\x8a\x03\x3f\x09\x20\xf1\x1f\xc7\x01\xf8\xa5\x5e\x49\xc5\xbf\x19\x4d\x14\x16\x1b\x5c\x68\x2e\x0b\xe8\x10\x00\x4e\x61\xce\x97\x1b\xa6\x38\xe6\x5d\xf3\xae\xeb\x7a\x66\x6a\x5f\xa8\x16\x2b\x54\x9d\xc1\x83\x07\x69\x14\xbe\xa5\x01\x44\x93\x04\xa2\x74\x3c\xae\xd4\x82\x09\xe9\x68\xec\xa2\x3d\x6a\x47\x15\x68\xb6\xd3\x8e\x00\xcf\xae\x32\xd4\xa0\xb9\x60\x1b\x8d\x62\xed\x68\x28\x6a\xbc\xec\x34\xcf\x34\x0e\x5f\xfd\x78\x06\x2f\xc1\x0c\x3a\x9c\x7a\xc4\x1b\x92\x3f\xa1\xf3\x5c\x6e\x19\x7d\x0e\xaf\x06\x2d\x50\xb0\xb3\xf5\xfb\x7e\xdf\xf5\x4e\xa5\x40\x5e\x34\xd7\xd7\xe5\x3c\xe7\x8b\xec\x93\xed\xe1\x57\xd0\x1f\xb8\x75\x3c\xec\x6e\xce\x75\x61\x9f\x78\x50\x07\x38\xa2\x0e\xa3\x51\xf0\x0e\xf8\xc1\xb3\xf9\x3e\x3b\x5a\x9a\x44\x76\xb0\xc3\xa1\x89\xde\xd2\x68\x79\x75\x9b\xeb\x42\x13\xbb\xd4\xf0\xba\x4a\xcf\x4c\x6e\x07\x68\x04\xb7\x18\x1a\xc9\x2d\x8c\xa5\xd9\x68\xff\x86\x17\x33\xfe\xcf\xd9\x6b\xa2\x5c\x56\xac\x1c\x4f\xd9\x69\x7d\x8d\xed\x00\xc4\x51\x75\x4f\x2e\xab\xc9\xc4\xbe\x85\x23\xb9\x2d\xc8\x28\x9e\x4c\xdb\x6e\xe1\xd0\x51\x9c\x3e\xce\xb5\xd3\x6a\xf7\x90\xfc\x04\x00\x00\xff\xff\x1a\x15\xdc\x7a\xe7\x03\x00\x00")

func migrations_compliance01_initSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations_compliance01_initSql,
		"migrations_compliance/01_init.sql",
	)
}

func migrations_compliance01_initSql() (*asset, error) {
	bytes, err := migrations_compliance01_initSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations_compliance/01_init.sql", size: 999, mode: os.FileMode(420), modTime: time.Unix(1472227636, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"migrations_gateway/01_init.sql": migrations_gateway01_initSql,
	"migrations_compliance/01_init.sql": migrations_compliance01_initSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"migrations_compliance": &bintree{nil, map[string]*bintree{
		"01_init.sql": &bintree{migrations_compliance01_initSql, map[string]*bintree{}},
	}},
	"migrations_gateway": &bintree{nil, map[string]*bintree{
		"01_init.sql": &bintree{migrations_gateway01_initSql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

