// Code generated by go-bindata.
// sources:
// migrations_gateway/01_init.sql
// migrations_compliance/01_init.sql
// DO NOT EDIT!

package postgres

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _migrations_gateway01_initSql = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x7c\x92\x41\x4f\xc3\x30\x0c\x85\xef\xf9\x15\x3e\x6e\x82\x49\x80\xd8\x2e\x3b\x15\x16\xa4\x89\xb2\x8d\xd2\x1e\x76\xaa\xb2\xc4\x2a\x11\x6d\x52\x25\xee\x18\xff\x9e\x0c\x09\xd6\x86\xc1\x31\xfa\x5e\x6c\x3f\x3f\x4f\x26\x70\xd1\xe8\xca\x09\x42\x28\x5a\x76\x9f\xf1\x24\xe7\x90\x27\x77\x29\x87\x0c\x25\xea\x3d\xaa\x8d\xf8\x68\xd0\x10\x8c\x18\x80\x56\xb0\xd3\x95\x47\xa7\x45\x7d\x19\xde\xb6\xc5\xf0\x57\x5b\x53\x06\xb2\x17\x4e\xbe\x0a\x37\xba\x99\x4e\xc7\x50\xac\x96\xcf\x05\x87\xd5\x3a\x87\x55\x91\xa6\x47\x71\xeb\xac\x44\xef\x51\x95\x82\x80\x74\x83\x9e\x44\xd3\x0e\x25\xa2\xd2\xa6\x2a\xc9\xbe\xa1\x19\xd6\xeb\xab\xc2\x3f\xea\xfc\xdf\x7c\x93\x2d\x9f\x92\x6c\x0b\x8f\x7c\x0b\x23\xad\xc6\x6c\x3c\x67\x43\x6f\x2f\xc1\x50\xee\x84\xf1\x42\x1e\xa7\xff\xf6\x76\x32\x46\x27\xd8\xb7\x36\xbb\xed\x75\x82\xdf\xa3\x5c\x5f\x45\x93\xda\xce\x49\xfc\xc1\xd3\x59\x84\xbb\x5d\xa3\x89\xfe\xdb\x88\xef\xa4\x44\x54\xb1\x64\xc1\x1f\x92\x22\x3d\xc9\x6a\x54\x15\xba\x63\x38\x3a\x44\x15\x53\x34\x7b\xac\x43\x56\xe5\x41\x39\x20\x3c\xd0\xa0\x85\x43\xdf\xd5\xf4\xc5\x06\x2b\x8d\xab\x9c\x5d\x6b\xff\x82\x16\xf6\xdd\xb0\x45\xb6\xde\x9c\xbf\xa0\x79\x9f\x45\x09\xcc\xd9\x67\x00\x00\x00\xff\xff\x4d\x61\x55\x6b\x8b\x02\x00\x00")

func migrations_gateway01_initSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations_gateway01_initSql,
		"migrations_gateway/01_init.sql",
	)
}

func migrations_gateway01_initSql() (*asset, error) {
	bytes, err := migrations_gateway01_initSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations_gateway/01_init.sql", size: 651, mode: os.FileMode(420), modTime: time.Unix(1473881382, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _migrations_compliance01_initSql = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x94\x93\xc1\x6e\xf2\x30\x10\x84\xef\x7e\x8a\x3d\x12\xfd\x70\xf9\x55\xb8\x70\x4a\x8b\x2b\x45\xa5\x81\x46\x89\x54\x4e\xd6\x82\x5d\xb0\x1a\xc7\xc8\x38\x05\xfa\xf4\x75\x4a\x21\x71\x21\xa0\x4a\xb9\xc4\x3b\xbb\x3b\xf3\x25\xee\xf5\xe0\x9f\x92\x4b\x83\x56\x40\xb6\x26\x0f\x09\x0d\x53\x0a\x69\x78\x3f\xa6\x10\x96\x76\xa5\x8d\xfc\x14\x3c\x35\x58\x6c\x70\x61\xa5\x2e\xa0\x43\x00\x24\x87\xb9\x5c\x6e\x84\x91\x98\x77\xdd\xbb\xad\xeb\xcc\xd5\x3e\xd0\x2c\x56\x68\x3a\x83\xbb\x00\xe2\x49\x0a\x71\x36\x1e\x57\x32\x25\x94\x6e\x2d\x36\x67\xec\xb8\x01\x2b\x76\xd6\x13\xe0\xc9\x0e\x43\x0b\x56\x2a\xb1\xb1\xa8\xd6\x9e\x86\xa3\xc5\xf3\x4e\xf7\x4c\x93\xe8\x39\x4c\x66\xf0\x44\x67\xd0\x91\x3c\x20\xc1\x90\xfc\x4a\x9b\xe7\x7a\x2b\xf8\x63\x74\x31\x61\x81\x4a\x9c\xac\xff\xef\xf7\x7d\xef\x5c\x2b\x94\x45\x7b\x7d\x5d\xce\x73\xb9\x60\xef\x62\x0f\xdf\x82\xfe\xc0\xaf\xe3\x61\x77\x7b\xae\x33\xfb\x24\x80\x3a\x40\x16\x47\x2f\x19\x85\x28\x1e\xd1\x57\xc0\x37\xc9\xe6\x7b\xf6\x63\x69\x12\x37\x83\x1d\x0e\x5d\xf4\x2b\x8d\x0d\xaf\x7e\x73\x5d\x68\x63\x97\x39\x5e\x17\xe9\xb9\xc9\xd7\x01\x3a\xc1\x2d\x86\x4e\x72\x0b\x63\xe9\x36\x36\xff\xbf\xb3\x19\x7f\xe7\x1c\xb4\x51\x2e\x2b\x56\x9e\x27\x76\x5c\x5f\x63\x3b\x00\xf1\x54\xdd\xa3\xcb\x6a\x32\x69\x5e\xbf\x91\xde\x16\x64\x94\x4c\xa6\xd7\xae\xdf\xd0\x53\x1c\x3f\xce\xa5\xd3\x6a\xf7\x90\x7c\x05\x00\x00\xff\xff\x02\xc5\x23\x8a\xe0\x03\x00\x00")

func migrations_compliance01_initSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations_compliance01_initSql,
		"migrations_compliance/01_init.sql",
	)
}

func migrations_compliance01_initSql() (*asset, error) {
	bytes, err := migrations_compliance01_initSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations_compliance/01_init.sql", size: 992, mode: os.FileMode(420), modTime: time.Unix(1475617538, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"migrations_gateway/01_init.sql": migrations_gateway01_initSql,
	"migrations_compliance/01_init.sql": migrations_compliance01_initSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"migrations_compliance": &bintree{nil, map[string]*bintree{
		"01_init.sql": &bintree{migrations_compliance01_initSql, map[string]*bintree{}},
	}},
	"migrations_gateway": &bintree{nil, map[string]*bintree{
		"01_init.sql": &bintree{migrations_gateway01_initSql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

